#  compose.yaml

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - spring-network
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand(\"ping\")" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
      #      - ME_CONFIG_MONGODB_PORT=27017
      #      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      #      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      #      - ME_CONFIG_MONGODB_URL=mongodb://root:secret@mongodb:27017/demo-database
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    ports:
      - '8081:8081'
    networks:
      - spring-network
    depends_on:
      mongodb:
        condition: service_healthy

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    command: redis-server --requirepass password
    volumes:
      - redis_data:/data
    networks:
      - spring-network
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  spring-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data: