#  application.yaml

spring:
  config:
    import: optional:classpath:env.properties

  application:
    name: ${SPRING_APP_NAME:spring-boot}

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD}
      timeout: 5000
      repositories:
        enabled: false

  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: false

logging:
  level:
    root: INFO
    com.example: DEBUG
    MongoDBTransactions: DEBUG
    RedisTransactions: DEBUG
    ServiceOperations: DEBUG
    org.springframework.boot.docker.compose: DEBUG
