spring:
  application:
    name: spring-boot-mongodb-redis

  data:
    mongodb:
      host: localhost
      port: 27017
      database: user_db
      username: root
      password: pass
      authentication-database: admin

    redis:
      host: localhost
      port: 6379
      password: password
      repositories:
        enabled: false

  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: false

logging:
  level:
    root: INFO
    com.example: DEBUG
    MongoDBTransactions: DEBUG
    RedisTransactions: DEBUG
    ServiceOperations: DEBUG
